apiVersion: v1
kind: Service
metadata:
  name: solrcluster
  labels:
    app: solr-app
spec:
  clusterIP: None
  selector:
    app: solr-app
---
apiVersion: v1
kind: Service
metadata:
  name: solr-service
  labels:
    app: solr-app
spec:
  ports:
  - port: 8983
    targetPort: 8983
    nodePort: 8983
    protocol: TCP
  selector:
    app: solr-app
  type: NodePort
